Add initial AssertJ assertions
valfirst/slf4j-test pull request #182
Opened 2021-07-27 07:36 UTC by jamietanna

As noted in #181, we can provide custom AssertJ assertions as a way to
simplify the ability to write unit tests against this library.

Closes #181.

2021-07-27 17:41 UTC, valfirst requested changes

2021-07-27 17:41 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/TestLoggerAssertions.java
> + * A set of assertions to validate that logs have been logged ot a {@link TestLogger}.
```suggestion
 * A set of assertions to validate that logs have been logged to a {@link TestLogger}.
```

2021-07-27 17:41 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/TestLoggerAssertions.java
> +            if (Collections.indexOfSubList(Arrays.asList(arguments), event.getArguments()) == -1) {
Doesn't simple `equals` work here?
```suggestion
            if (event.getArguments().equals(Arrays.asList(arguments))) {
```

2021-07-27 17:41 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/TestLoggerAssertions.java
> +            return true;
```suggestion
            return event.getThrowable().equals(maybeThrowable);
```

2021-07-27 17:41 UTC, valfirst commented on src/test/java/com/github/valfirst/slf4jtest/TestLoggerAssertionsTest.java
> +        );
```suggestion
        assertions = Assertions.assertThat(logger);
```

2021-07-27 17:41 UTC, valfirst commented on src/test/java/com/github/valfirst/slf4jtest/TestLoggerAssertionsTest.java
> +}
please add an empty line in the end of the file

2021-07-28 21:27 UTC, jamietanna commented on src/main/java/com/github/valfirst/slf4jtest/TestLoggerAssertions.java
> +            if (Collections.indexOfSubList(Arrays.asList(arguments), event.getArguments()) == -1) {
Doh! Yep good point

2021-07-29 07:19 UTC, valfirst requested changes

2021-07-29 07:19 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/AbstractTestLoggerAssert.java
> +            }
```suggestion
```
I believe it's not needed, because `List.equals` already contains this check

2021-07-29 07:19 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/AbstractTestLoggerAssert.java
> +            return true;
```suggestion
            return message.equals(event.getMessage()) && event.getArguments().equals(Arrays.asList(arguments))
                    && event.getThrowable().equals(maybeThrowable);
```
?

2021-07-29 07:20 UTC, valfirst commented
@jamietanna do you keep the PR in draft state intentionally?

2021-07-29 07:31 UTC, jamietanna commented
> @jamietanna do you keep the PR in draft state intentionally?

Sorry, I'll mark ready now I've finished implementation + fixed up the Git history

2021-07-29 08:08 UTC, valfirst approved these changes

2021-07-29 08:14 UTC, merged

2021-07-29 08:15 UTC, valfirst commented
@jamietanna thank you for your contribution!

2021-07-29 08:16 UTC, jamietanna commented
You're very welcome - thanks for picking up maintainence fo the library!

Will this get automagically released? :smile:

2021-07-29 08:17 UTC, valfirst commented
Not yet automatically, but I'll release it in a couple hours

2021-07-29 09:55 UTC, valfirst commented
@jamietanna 
The release is published:
- https://repo1.maven.org/maven2/com/github/valfirst/slf4j-test/2.2.0/
- https://github.com/valfirst/slf4j-test/releases/tag/slf4j-test-2.2.0