Avoid excessive copying of the MDC
valfirst/slf4j-test pull request #406
Opened 2023-06-14 20:38 UTC by karstenspang

This PR answers some of the concerns raised in #391 "Do we really need copies to be immutable?"

It turned out that the main issue was around the copy of the MDC returned by `TestMDCAdaptor.getCopyOfContextMap()`. The [specification in SLF4J](https://www.slf4j.org/apidocs/org/slf4j/MDC.html#getCopyOfContextMap--) says nothing about whether the copy is immutable. There is no reason for it to be so, since the returned objects is fully owned by the caller.

A related issue is that `LoggingEvent` creates its own copy of the returned object. This leads to excessive copying, in particular because the map is usually empty.

My solution:
 * Make `getCopyOfContextMap()` return a modifiable copy. This makes it unneccesary for the client to make yet another copy.
 * Create a new package private method `TestMDCAdaptor.getContextMap()` that returns a reference to map kept in the MDC adaptor. This is used by `TestLogger` when constructing a `LoggingEvent`.
 * `LoggingEvent` in turn makes its own copy of the MDC passed to the constructor. Before actually making a copy, it is checked whether the MDC is empty. If so, the (singleton) `Collections.emptySortedMap()` is called instead.

Furthermore, I have made it explicit that `LoggingEvent.getMdc()` returns a `SortedMap`. I have chosen this because having a well-defined ordering of the map makes it easier to spot discrepancies in case an assertion fails.

The changes I made for #392 unintentionally allowed an `mdc` argument transferred to the `LoggingEvent` constructor to be null. I have reverted that change.

I noticed that the specification for [`MDC.setContextMap`](https://www.slf4j.org/apidocs/org/slf4j/MDC.html#setContextMap-java.util.Map-) says that the current map is cleared before being replaced. I have corrected the code to reflect this.

2023-06-15 07:12 UTC, valfirst requested changes

2023-06-15 07:12 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/TestMDCAdapter.java
> +                return new HashMap<>();
```suggestion
                return new TreeMap<>();
```
?

2023-06-15 07:12 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/TestMDCAdapter.java
> +            return new HashMap<>(map);
```suggestion
            return new TreeMap<>(map);
```
?

2023-06-15 07:12 UTC, valfirst commented on src/main/java/com/github/valfirst/slf4jtest/LoggingEvent.java
> +                mdc.isEmpty()
```suggestion
                requireNonNull(mdc).isEmpty()
```
?

2023-06-15 08:07 UTC, karstenspang commented on src/main/java/com/github/valfirst/slf4jtest/LoggingEvent.java
> +                mdc.isEmpty()
OK with me. It is more understandable.

2023-06-15 08:51 UTC, valfirst approved these changes

2023-06-15 08:52 UTC, merged

2023-06-15 08:53 UTC, valfirst commented
@karstenspang thank you for your contribution! do you plan to add anything in the near future? otherwise I'll proceed with `3.0.0` release

2023-06-25 12:00 UTC, karstenspang commented
@valfirst Sorry, didn't notice the question in you last comment. No I don't plan to make any further changes.